name: marvel_comics
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  crypto: 3.0.2
  dio: 4.0.6
  flutter:
    sdk: flutter
  freezed_annotation: 2.1.0
  json_annotation: 4.6.0
  native_flutter_proxy: 0.1.15
  retrofit: 3.0.1+1

dev_dependencies:
  build_runner: 2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  freezed: 2.1.0+1
  json_serializable: 6.3.1
  mocktail: 0.3.0
  retrofit_generator: 4.0.3+1

flutter:
  uses-material-design: true
